resource_group_name   = "dev-rg"
location              = "East US"
storage_account_name  = "devstorage"
container_name        = "tfstate"
app_service_plan_name = "appserviceplan"
cosmosdb_account_name = "cosmosdb-dev"
